image: cypress/included:12.0.0  

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/ 

before_script:
  - npm install  

e2e_tests:
  stage: test
  script:
    - npx cypress run  
  artifacts:
    when: always
    paths:
      - cypress/screenshots  
      - cypress/videos  
  reports:
    junit:
      - cypress/results/*.xml  
